services:
  - type: web
    name: hrm-laravel
    env: docker
    plan: free
    # Dockerfile commands will be used, so no buildCommand/startCommand here
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: tramway.proxy.rlwy.net
      - key: DB_PORT
        value: "13864"
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: kXaenOYGCHwhRqjTWcojJQrHOMFiPfYi
      - key: APP_DEBUG
        value: "false"
      - key: LOG_CHANNEL
        value: stack
